lv_five/five_app/urls.py
from django.urls import path
from five_app import views

#TEMPLATE URLs
app_name='five_app'
urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),

]

lv_five/lv_five/urls.py
from django.contrib import admin
from django.urls import path,include
from five_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('five_app/',include('five_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

lv_five/five_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    #addithional
    portfolio_site=models.URLField(blank=True)

    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

lv_five/five_app/forms.py
from django import forms
from django.contrib.auth.models import User
from five_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

lv_five/five_app/views.py
from django.shortcuts import render,redirect
from five_app.forms import UserForm,UserProfileInfoForm

#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
#from django.core.urlresolvers import reverse  #in newrversion dont need to import this
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,"five_app/index.html")

@login_required
def special(request):
    return HttpResponse("you are logged in NICE!")


@login_required
def user_logout(request):
    logout(request)
    return redirect("index")

def register(request):

    registered=False

    if request.method == 'POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user #UserProfileInfoForm onetoone relation with User

            if 'profile_pic' in request.FILES: #to find the file it used when uplod any kind of file
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()
            registered=True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,"five_app/registration.html",{'user_form':user_form,
                                                        'profile_form':profile_form,
                                                        'registered':registered})



def user_login(request): #name of view cannot be equal to imported functions
    if request.method=='POST':
        username=request.POST.get('username') #grab data from html
        password=request.POST.get('password')

        user=authenticate(username=username,password=password) #chek provided data is True or not

        if user:
            if user.is_active:
                login(request,user) #login
                return redirect('index') #redirect the user to whatever the page you provide

            else:
                return HttpResponse("Account not active")

        else:
            print("someone try to login and failled")
            print("Username: {} and password: {} is not riht".format(username,password))
            return HttpResponse("invalid login details ")
    else:
        return render(request,'five_app/login.html',{})

lv_five/templates/five_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}"></a>HOME</li>
          <li><a class="navbar-brand" href="{% url 'admin:index' %}"></a>Admin</li>
          <li><a class="navbar-brand" href="{% url 'five_app:register' %}"></a>Registration</li>

          {% if user.is_authenticated %}
            <li><a class="navbar-brand" href="{% url 'logout' %}"></a>Logout</li>

          {% else %}
            <li><a class="navbar-brand" href="{% url 'five_app:user_login' %}"></a>Login</li>

          {% endif %}

        </ul>


      </div>
    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

lv_five/templates/five_app/index.html
<!DOCTYPE html>

{% extends "five_app/base.html" %}

{% block body_block %}
 <div class="jumbotron">
   <h1>Djano level five </h1>

 </div>
{% endblock %}

lv_five/templates/five_app/login.html
{% extends 'five_app/base.html' %}

{% block body_block %}
<div class="jumbotron">
  <h1>Please Login </h1>
  <form  action="{% url 'five_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>
</div>
{% endblock %}

lv_five/templates/five_app/registration.html
{% extends "five_app/base.html"%}
{% load static %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank You for Registration</h1>
  {% else %}
  <h1>Register here </h1>
  <h3>Fill Out The Form </h3>
  <form enctype="multipart/form-data" method="post"> <!--enctype is used cause required in image uploading -->
    {% csrf_token %}
    {{user_form.as_p }}
    {{profile_form.as_p }}
    <input type="submit" name="" value="REGISTER">
  </form>
  {% endif %}

</div>
{% endblock %}